SITES-365: Fetch remaining information from snow API stub out
SU-SWS/Stanford-Drupal-Profile pull request #109
Opened 2018-09-07 18:35 UTC by sherakama

# NOT READY

WAITING ON API

2018-09-07 18:36 UTC, jbickar commented
You fancy.

2018-09-10 16:25 UTC, sherakama commented on stanford.profile
> +  return 'acsf';
Don't forget to remove this after you are done testing.

2018-09-10 16:27 UTC, jbickar commented on stanford.profile
> +  return 'acsf';
"You" being Shea, or "you" being John?

2018-09-10 16:29 UTC, sherakama commented on stanford.profile
> +  return 'acsf';
Reminder to myself or a potential reviewer.

2018-12-12 17:38 UTC, jbickar commented
Merge conflict here that I don't fully understand.

2018-12-12 17:52 UTC, sherakama commented
@jbickar it would help if I were able to copy pasta correctly. Somehow the stanford_ssp module got in here.

Revised and ready for review.

2018-12-12 17:55 UTC, jbickar commented
LOL, thank you. I saw that in there and was like, "Uh, why are you not re-purposing that module? I thought we had that discussion already." 😂

2018-12-12 18:04 UTC, jbickar commented
Ah, that's a much more readable PR.

2018-12-12 18:29 UTC, jbickar requested changes
Beautiful. A few comments and requests for clarifications.

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> +    'syslog',
This is weird. This was added in #110; why is it re-appearing here?

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> +  drupal_static_reset();
A code comment here explaining why would be helpful.

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> + * The remaining information is available in ritm and has been exposed through
```suggestion
 * The remaining information is available in the RITM ("Request Item" in ServiceNow) and has been exposed through
```

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> +  global $conf;
Code comment here would be helpful. Why is $conf not available yet at this point?

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> +  // Fetch the json from the ritm service now endpoint.
```suggestion
  // Fetch the json from the ServiceNow (SNOW) API endpoint that exposes the RITM information.
```

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> +  $site_name = isset($install_vars['forms']['install_configure_form']['site_name']) ? check_plain($install_vars['forms']['install_configure_form']['site_name']) : NULL;
(_Comments under his breath about the lack of readability of the ternary operator_)

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> +  $site_name = isset($install_vars['forms']['install_configure_form']['site_name']) ? check_plain($install_vars['forms']['install_configure_form']['site_name']) : NULL;
Thank you for sanitizing that variable.

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> +  if (!isset($response['sunetId'])) {
Hm. What other scenarios could exist other than `!isset()` that we should trigger an exception? let's think on this; maybe just note as a code comment.

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> + * Fetches json information from the service now api.
```suggestion
 * Fetches JSON information from the ServiceNow (SNOW) API.
```

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> +
```suggestion

// Database variables are not yet available or reliable at this point. This will have to be hard-coded in settings.php
// or the like if you wish to override the default.
```

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> +function stanford_acsf_tasks_ritm_make_api_request($sitename) {
Meh, perhaps an OCD detail, but you define the function with `$sitename`, yet call it above with `$site_name`. My sense of order and harmony in the universe would like to see them reconciled.

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> +  $username = variable_get('stanford_snow_api_user', '');
Do we care about sanitizing this and the password?

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> +  $response = stanford_acsf_tasks_ritm_make_api_request($site_name);
I would like to see an example of the object that `stanford_acsf_tasks_ritm_make_api_request()` returns. I'm not sure if it's appropriate here, in the function definition, or the `README`.

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> +  module_load_include('inc', 'stanford_ssp', 'stanford_ssp.admin');
w00t. DRY.

2018-12-12 18:29 UTC, jbickar commented on stanford.profile
> +  if (isset($response['webSiteOwners'])) {
Ehrmagerd, this alone will save me countless hours.

2018-12-12 18:41 UTC, sherakama commented on stanford.profile
> +    'syslog',
Not sure. Looks like it is in 3.x as this PR shows it.

2018-12-12 18:41 UTC, sherakama commented on stanford.profile
> +  drupal_static_reset();
Ah, that was for troubleshooting the user role issue. Don't need this after all.

2018-12-12 18:44 UTC, sherakama commented on stanford.profile
> +  global $conf;
It is available, just making sure I pull the variable from the global scope in to this function's scope.

2018-12-12 18:45 UTC, jbickar commented on stanford.profile
> +  global $conf;
Ah, right. Carry on.

2018-12-12 18:46 UTC, sherakama commented on stanford.profile
> +  if (!isset($response['sunetId'])) {
This is one of many places the I trigger exceptions when validating the response object. This may be redundant after everything else.

2018-12-12 18:49 UTC, sherakama commented on stanford.profile
> +  $username = variable_get('stanford_snow_api_user', '');
Pulling from the database is not the same as user input. Items out of `variable_get()` should be trustworthy.

2018-12-12 18:58 UTC, jbickar commented on stanford.profile
> +  $username = variable_get('stanford_snow_api_user', '');
Yeah, there's no end-user interface for this variable. It doesn't look like `variable_set()` or `variable_get()` sanitizes strings, but if someone has DB or drush access to your site, or they have write access to your codebase, especially at install time, you're already owned.

2018-12-12 20:52 UTC, sherakama commented on stanford.profile
> +function stanford_acsf_tasks_ritm_make_api_request($sitename) {
This has been changed.

2018-12-12 20:52 UTC, sherakama commented on stanford.profile
> +  $response = stanford_acsf_tasks_ritm_make_api_request($site_name);
I have added it to the function docblock.

2018-12-12 20:53 UTC, sherakama commented
@jbickar requested changes applied.

2018-12-12 21:04 UTC, jbickar commented on stanford.profile
> + *    "webSiteTitle": "Meddle",
I'm going to make a small change here to indicate that `webSiteTitle` can have spaces in it.

2018-12-12 21:11 UTC, jbickar commented
[That'll do, Canada. That'll do.](https://www.youtube.com/watch?v=rjQtzV9IZ0Q)

This will save me countless minutes, which I can use to watch cat videos.

2018-12-12 21:12 UTC, jbickar approved these changes

2018-12-12 21:12 UTC, merged

2018-12-12 21:12 UTC, jbickar commented
w00t 🎉